### ISSUE TITLE
.hdr format passthrough

### ISSUE THREAD

**Issue by ConorWoodard** [paradowskicreative/ZenCompress#1]
This is an excellent tool! It fails to export with .glb files that have .HDR in them. Basisu doesn't currently support .HDR formats, but it would be extremely helpful if this tool could safely pass them through while still working on compatible file types.

**Comment by EthanMichalicek** [comment]
> This is an excellent tool! It fails to export with .glb files that have .HDR in them. Basisu doesn't currently support .HDR formats, but it would be extremely helpful if this tool could safely pass them through while still working on compatible file types.

This is something we will work on, Conor!

**Comment by EthanMichalicek** [comment]
This feature has been added! HDR is now supported as passthrough when using the `MOZ_texture_rgbe` extension.

https://github.com/paradowskicreative/ZenCompress/releases/tag/1.4.3
